spring.application.name=application


logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.access.intercept.FilterSecurityInterceptor=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/SmartHealthTracking
spring.datasource.username=postgres
spring.datasource.password=andrei
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 2. JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=4pZ9X7jY2mK5vL8nQ1rS4uW7xZ0a3d6g9j2m5p8s1v4y7z0b3e6h9k2n5r8uW1xZ

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#CLOUDINARY


cloudinary.cloud-name=dkaq5h4ob
cloudinary.api-key=175562485895746
cloudinary.api-secret=lHUG0ay97frVqihTO-rqBUJHGMA


#GEMINI PRIN API KEY


spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/


spring.ai.openai.api-key=AIzaSyDSfXLlgaa27543jIdU0_kOgKPnTkCIjEA


# 3. Modelul Gemini pe care vrei s? îl folose?ti (Flash este ideal pentru vitez? ?i corel?ri)
spring.ai.openai.chat.options.model=gemini-3-flash-preview








spring.jpa.properties.hibernate.format_sql=true
