spring.application.name=application


logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.access.intercept.FilterSecurityInterceptor=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/SmartHealthTracking
spring.datasource.username=postgres
spring.datasource.password=andrei
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 2. JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=4pZ9X7jY2mK5vL8nQ1rS4uW7xZ0a3d6g9j2m5p8s1v4y7z0b3e6h9k2n5r8uW1xZ






spring.jpa.properties.hibernate.format_sql=true
