spring.application.name=application

logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.access.intercept.FilterSecurityInterceptor=DEBUG

# Baza de date (folose?te o variabil? de mediu sau las? localhost dac? parola e simpl?, dar e mai bine s? o ascunzi)
spring.datasource.url=jdbc:postgresql://localhost:5432/SmartHealthTracking
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:andrei}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT - Citit din variabila JWT_SECRET, cu o valoare default doar pentru backup local
jwt.secret=${JWT_SECRET:schimba-ma-cu-un-string-lung-si-sigur-la-nevoie}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CLOUDINARY
cloudinary.cloud-name=dkaq5h4ob
cloudinary.api-key=175562485895746
cloudinary.api-secret=${CLOUDINARY_SECRET}

# GEMINI PRIN API KEY
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.chat.options.model=gemini-3-flash-preview

# CONFIGURARE SISTEM DE MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wellsync123@gmail.com
spring.mail.password=${EMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true